export const USER_LOGGEDIN_SUCCESS = 'USER_LOGGEDIN_SUCCESS';
export const USER_LOGGEDIN_FAILURE = 'USER_LOGGEDIN_FAILURE';
export const USER_LOGGEDIN_LOADING = 'USER_LOGGEDIN_LOADING';
export const USER_LOGGEDOUT = 'USER_LOGGEDOUT';

export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';
export const USER_REGISTRATION_LOADING = 'USER_REGISTRATION_LOADING';

export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_FAILURE = 'UPDATE_USER_DETAILS_FAILURE';
export const UPDATE_USER_DETAILS_LOADING = 'UPDATE_USER_DETAILS_LOADING';