export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAILURE = 'ORDER_CREATE_FAILURE';
export const ORDER_CREATE_LOADING = 'ORDER_CREATE_LOADING';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const USER_ORDERS_SUCCESS = 'USER_ORDERS_SUCCESS';
export const USER_ORDERS_FAILURE = 'USER_ORDERS_FAILURE';
export const USER_ORDERS_LOADING = 'USER_ORDERS_LOADING';
export const USER_ORDERS_RESET = 'USER_ORDERS_RESET';